export type Opportunity = {
  id: string;
  slug: string;
  title: string;
  description: string | null;
  provider_id: string | null;
  provider_name: string | null;
  category: string | null;
  age_min: number | null;
  age_max: number | null;
  city: string | null;
  location_name: string | null;
  address: string | null;
  start_date: string | null;
  end_date: string | null;
  registration_deadline: string | null;
  cost_type: string | null;
  cost_amount: number | null;
  registration_url: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  source_url: string | null;
  image_url: string | null;
  status: string;
  featured: boolean;
  created_at: string;
  updated_at: string;
};
